version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY:-change-me}"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dokerker_db
      DB_USER: tab1k
      DB_PASSWORD: TOBI8585
      PORT: 8000
      DJANGO_SUPERUSER_USERNAME: tab1k
      DJANGO_SUPERUSER_PASSWORD: TOBI8585
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - static_data:/app/src/staticfiles
      - media_data:/app/src/media

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dokerker_db
      POSTGRES_USER: tab1k
      POSTGRES_PASSWORD: TOBI8585
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  static_data:
  media_data:
