# Generated by Django 6.0.3 on 2026-04-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL-код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-код')),
                ('sku', models.CharField(max_length=80, unique=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('material', models.CharField(default='PE 100', max_length=80, verbose_name='Материал')),
                ('sdr', models.CharField(default='SDR 11', max_length=20, verbose_name='SDR')),
                ('pressure_rating', models.CharField(default='PN 16', max_length=30, verbose_name='Давление')),
                ('standard', models.CharField(default='EN 12201 / ISO 8085', max_length=120, verbose_name='Стандарт')),
                ('application', models.CharField(blank=True, max_length=180, verbose_name='Применение')),
                ('diameter_mm', models.PositiveIntegerField(verbose_name='Основной диаметр DN, мм')),
                ('outlet_diameter_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Диаметр отвода DN, мм')),
                ('reduced_diameter_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Переход на DN, мм')),
                ('angle_degree', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Угол, °')),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина, мм')),
                ('welding_voltage_v', models.PositiveIntegerField(blank=True, null=True, verbose_name='Напряжение сварки, В')),
                ('welding_time_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время сварки, сек')),
                ('cooling_time_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время охлаждения, мин')),
                ('barcode', models.CharField(blank=True, max_length=80, verbose_name='Штрихкод')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена, ₸')),
                ('stock_status', models.CharField(choices=[('in_stock', 'На складе'), ('preorder', 'Под заказ'), ('out_of_stock', 'Нет в наличии')], default='in_stock', max_length=20, verbose_name='Наличие')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток, шт')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок поставки, дней')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Фото')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный товар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('category__sort_order', 'sort_order', 'name'),
                'indexes': [models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'), models.Index(fields=['diameter_mm'], name='products_pr_diamete_7c550e_idx'), models.Index(fields=['stock_status'], name='products_pr_stock_s_5ad318_idx')],
            },
        ),
    ]
